fix: handle gateway.wsConnectionParams
mcollina/fastify-gql pull request #265
Opened 2020-08-26 14:45 UTC by PacoDu

This PR fixes the `gateway.service.wsConnectionParams` that is currently defined in the documentation but not handled.

It also adds the `connection_error` message handling for the `SubscriptionClient` and the `connectionInitPayload` option.

2020-08-26 22:24 UTC, mcollina approved these changes
lgtm

2020-08-27 07:34 UTC, PacoDu commented
A little change so that `gateway.service.wsConnectionParams.connectionInitPayload` can be an async function.

2020-08-27 08:07 UTC, mcollina requested changes
Please add tests for the error paths where the new function throws.

2020-08-27 08:07 UTC, mcollina commented on lib/subscription-client.js
> +    this.socket.onopen = async () => {
Can you add a try/catch? The `connectionInitPayload` can throw, and it will lead to an unhandledRejection

2020-08-29 18:34 UTC, PacoDu commented
is there anything that prevent this PR from being merged ?

2020-08-30 00:07 UTC, mcollina approved these changes
nothing,

LGTM

2020-08-30 00:07 UTC, merged